version: '3'

services:

  app:
    build:
      context: node
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    networks:
      - mynetwork
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: 
      - --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - mynetwork

  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    networks: 
      - mynetwork
    ports: 
      - "8080:80"

networks:
  mynetwork:
    driver: bridge